name: Deploy Backend ðŸš¢

on:
  push:
    branches:
      - backend-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ›Ž Checkout
        uses: actions/checkout@v2
      - name: ðŸ—º Navigate to backend directory
        run: cd backend
      - name: Deploy backend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "onmangetuca-backend"
          heroku_email: "olivier@glo.quebec"

